// pages/index.vue
<template>
  <div :class="{container: true, 'light-bg': lightBackground}">
    <main>
      <section :class="$style.splash" id="splash" v-viewport-overlap="overlapHandler">
        <h1>Whiskey ginger&nbsp;&amp; a&nbsp;dash&nbsp;of bitters.</h1>
      </section>

      <section :class="$style.bio" id="bio" v-viewport-overlap="overlapHandler">
        <h2>Bio</h2>

        <p>Hello! I’m Zak Johnson, a design-minded full-stack developer with
        a background in information security. I’ve been building and breaking
        things on the web since the nineties at companies like
        <a href="https://www.etsy.com/">Etsy</a>,
        <a href="https://www.good.is/">GOOD</a>, and
        <a href="http://madebycabin.com/">Cabin</a>. I currently lead a team
        of product engineers at
        <a href="https://mixpanel.com/">Mixpanel</a>.</p>

        <p>I’m passionate about simplicity,
        <a href="https://github.com/zakj/dotfiles/blob/master/vimrc">text
        editors</a>,
        <a href="https://www.python.org/">significant whitespace</a>, and
        <a href="https://brians.wsu.edu/common-errors-in-english-usage/">grammar</a>.</p>
      </section>

      <section :class="$style.history" id="history" v-viewport-overlap="overlapHandler">
        <h2>History</h2>
      </section>

      <section :class="$style.code" id="code" v-viewport-overlap="overlapHandler">
        <h2>Code</h2>
      </section>

      <section :class="$style.qa" id="qa" v-viewport-overlap="overlapHandler">
        <h2>Q / A</h2>
      </section>
    </main>

    <BackgroundView />
    <HeaderLogo />
    <NavMenu />
    <SocialMenu />
  </div>
</template>

<style lang="stylus" module>
  .splash
    align-items center
    display flex
    // background-image url('~/assets/splash-bg.jpg')
    // background-size cover
    // background-position bottom right

  .bio
    // background-color #dbc69e
    // transition background-color 200ms ease-in

  .history
    // background-color #1d7c87

  .code
    // background-color #fff
    // color $dark-text-color

  .qa
    // background-color #4a4a4a
</style>

<script>
  import {mapGetters, mapMutations} from 'vuex';

  import BackgroundView from '~/components/background-view';
  import HeaderLogo from '~/components/header-logo';
  import NavMenu from '~/components/nav-menu';
  import SocialMenu from '~/components/social-menu';

  export default {
    head: {
      title: 'Zak Johnson',
      meta: [
        {hid: 'description', name: 'description', content: 'XXX'},
      ],
    },

    components: {BackgroundView, HeaderLogo, NavMenu, SocialMenu},

    computed: {
      greatestOverlapElement() {
        return this.elementOverlaps
          .map(([el, overlap]) => ({el, overlap}))
          .filter(({overlap}) => overlap > 0)
          .sort((a, b) => b.overlap - a.overlap)
          .map(({el}) => el)[0] || null;
      },

      ...mapGetters(['lightBackground']),
    },

    data() {
      return {
        elementOverlaps: [],
      }
    },

    methods: {
      overlapHandler(el, overlap) {
        // Vue is not reactive on Map, so we translate as needed.
        const map = new Map(this.elementOverlaps);
        // TODO: pass name from callers, just use an object?
        map.set(el, overlap);
        this.elementOverlaps = Array.from(map);
      },

      ...mapMutations(['setCurrentSection']),
    },

    watch: {
      greatestOverlapElement: function(section) {
        this.setCurrentSection(section.id);
      },
    },
  };
</script>

// pages/index.tsx
import Head from 'next/head';
import Markdown from 'react-markdown';
import React, { useRef, RefObject } from 'react';
import { useToggle } from 'react-use';
import styled from 'styled-components';

import useMostVisibleElement from 'src/use-most-visible-element';
import Mark from 'components/mark';
import Nav from 'components/nav';
import Social from 'components/social';
import { SectionName, SectionRefs } from 'src/sections';
import media from 'style/media';

export default () => {
  const sections: SectionRefs = {
    [SectionName.Splash]: useRef<HTMLElement>(null),
    [SectionName.Bio]: useRef<HTMLElement>(null),
    [SectionName.History]: useRef<HTMLElement>(null),
  };
  function sectionFromRef(ref: RefObject<HTMLElement>): SectionName | null {
    const key = Object.keys(sections).find(s => sections[s as SectionName] === ref);
    return key as SectionName || null;
  }

  const currentSection = useMostVisibleElement(Object.values(sections));
  const sectionName = (currentSection && sectionFromRef(currentSection)) ?? SectionName.Splash;
  const [socialMenuOpen, setSocialMenuOpen] = useToggle(false);

  function scrollIntoView(section: SectionName): void {
    sections[section].current?.scrollIntoView({behavior: 'smooth'});
  }

  function clickMark() {
    setSocialMenuOpen(false);
    scrollIntoView(SectionName.Splash);
  }

  return (
    <main>
      <Head>
        <title>Zak Johnson &middot; zakj.net</title>
      </Head>

      <Splash id="splash" ref={sections[SectionName.Splash]}>
        <h1>Whiskey ginger&nbsp;&amp; a&nbsp;dash&nbsp;of bitters.</h1>
      </Splash>

      <Section id="bio" ref={sections[SectionName.Bio]}
        style={{ minHeight: '200vh' }}  // XXX
      >
        <h2>Bio</h2>
        <Markdown
          source={`
Hello! I’m Zak Johnson, a design-minded full-stack developer with a
background in information security. I’ve been building and breaking things on
the web since the nineties at companies like [Etsy][], [GOOD][], and
[Cabin][]. I currently lead a team of product engineers at [Mixpanel][].

I’m passionate about simplicity, [text editors][vimrc], [significant
whitespace][python], and [grammar][common-errors].

[Etsy]: https://www.etsy.com/
[GOOD]: https://www.good.is/
[Cabin]: https://madebycabin.com/ 
[Mixpanel]: https://mixpanel.com/
[Grammarly]: https://www.grammarly.com/
[vimrc]: https://github.com/zakj/dotfiles/blob/master/vimrc
[python]: https://www.python.org/
[common-errors]: https://brians.wsu.edu/common-errors-in-english-usage/
      `}
        />
      </Section>

      <Section id="history" ref={sections[SectionName.History]}>
        history TODO
      </Section>

      <Nav sectionName={sectionName} onClick={scrollIntoView} />
      <Social open={socialMenuOpen} onClick={setSocialMenuOpen} />
      <Mark expanded={socialMenuOpen} onClick={clickMark} />
    </main>
  );
};


const paddingSmall = '24px';  // XXX move to theme?

const Section = styled.section`
  min-height: 100vh;
  padding: var(--padding);
`;

const Splash = styled(Section)`
  background: #eee;  /* XXX */
  display: flex;
  flex-direction: column;
  justify-content: center;

  h1 {
    font-size: 12vw;
    line-height: 0.9;
    /* max-width: calc(100vw - ${p => p.theme.padding.small} * 4); */
    max-width: calc(100vw - var(--padding) * 4);
    text-transform: uppercase;
    ${media.large} {
      font-size: 10vw;
    }
  }
`;
